### ISSUE TITLE
Clean calendly links in some of the event descriptions

### ISSUE THREAD

**Issue by gasharova** [MLH-Fellowship/calendar-site#5]
![image](https://user-images.githubusercontent.com/19854557/97913565-241a5d80-1d57-11eb-9a56-d1ec35833b50.png)

**Comment by gasharova** [comment]
For some reason I can't assign myself.
### im starting to work on the issue ###

**Comment by wrussell1999** [comment]
Great start! 

So we could probably fix all the break points using similar code I wrote for the Discord Bot that makes announcements. Here's a link to the code of that: https://github.com/MLH-Fellowship/event-bot/blob/cc129c4786ff905df388e196a9c8c0f1867219a9/app/schedule/cal.py#L53

![Screenshot 2020-11-03 at 12 12 44](https://user-images.githubusercontent.com/34094921/97983899-e278c980-1dcd-11eb-991c-aca79657a065.png)

**Comment by wrussell1999** [comment]
I had a go: https://github.com/MLH-Fellowship/calendar-site/pull/7/commits/e71de0f923d681c82790db6f114aaa7f2e3f3285

However, I can't get it to actually add new lines to the description. Just makes a big wall of text hmmm.

**Comment by wrussell1999** [comment]
Ah JQuery was rendering as plain text. If you tell the description to render as HTML, it renders better!

**Comment by wrussell1999** [comment]
Fixed by https://github.com/MLH-Fellowship/calendar-site/pull/7
